import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Monica',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mandapati',
      email: 'mandapati@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Womens Polo Shirt',
      slug: 'aero-polo-shirt',
      category: 'Shirts',
      image: '/images/aero_shirt1.jpeg',
      price: 20,
      countInStock: 10,
      brand: 'Aeropostale',
      rating: 4.5,
      numReviews: 5,
      description: 'Aeropostale Womens Polo Shirt',
    },
    {
      //_id: '2',
      name: 'Womens Graphic T Shirt',
      slug: 'aero-tee',
      category: 'Shirts',
      image: '/images/aero_tee.jpeg',
      price: 15,
      countInStock: 5,
      brand: 'Aeropostale',
      rating: 5,
      numReviews: 3,
      description: 'Aeropostale Womens Graphic Tee',
    },
    {
      //_id: '3',
      name: 'Womens Crop Top',
      slug: 'tommy-crop',
      category: 'Shirts',
      image: '/images/tommy_crop.jpeg',
      price: 10,
      countInStock: 7,
      brand: 'Tommy Hilfiger',
      rating: 3,
      numReviews: 2,
      description: 'Tommy Hilfiger Womens Crop Top',
    },
    {
      //_id: '4',
      name: 'Womens White Shirt',
      slug: 'tommy-white',
      category: 'Shirts',
      image: '/images/tommy_white.jpeg',
      price: 10,
      countInStock: 7,
      brand: 'Tommy Hilfiger',
      rating: 3,
      numReviews: 2,
      description: 'Tommy Hilfiger Womens White Shirt',
    },
    {
      //_id: '5',
      name: 'Womens T Shirt',
      slug: 'holister-tshirt',
      category: 'Shirts',
      image: '/images/holister_tshirt.jpeg',
      price: 25,
      countInStock: 2,
      brand: 'Holister',
      rating: 5,
      numReviews: 1,
      description: 'Holister Womens T Shirt',
    },
    {
      //_id: '6',
      name: 'Womens Blue Shirt',
      slug: 'holister-blue',
      category: 'Shirts',
      image: '/images/holister_blue.jpeg',
      price: 25,
      countInStock: 0,
      brand: 'Holister',
      rating: 5,
      numReviews: 1,
      description: 'Holister Womens Blue Shirt',
    },
    {
      //_id: '7',
      name: 'Womens Tee Shirt',
      slug: 'gap-shirt',
      category: 'Shirts',
      image: '/images/gap_shirt.jpeg',
      price: 30,
      countInStock: 6,
      brand: 'GAP',
      rating: 4.5,
      numReviews: 5,
      description: 'GAP Womens Tee Shirt',
    },
  ],
};

export default data;
